-- Migration: Enable Extensions and Create Enums
-- Purpose: Enable required PostgreSQL extensions and create custom enum types
-- Affected: Database-wide extensions and flashcard_source enum type
-- Created: 2025-10-14

-- Enable pgcrypto extension for UUID generation and cryptographic functions
create extension if not exists pgcrypto;

-- Enable pg_trgm extension for trigram-based text search
create extension if not exists pg_trgm;

-- Create enum type for flashcard source
-- This enum tracks whether a flashcard was created manually by the user or generated by AI
create type flashcard_source as enum ('manual', 'ai');


